### ISSUE TITLE
Wrong code snippet in the second step

### ISSUE THREAD

**Issue by stof** [knpuniversity/symfony-alice-fixtures#1]
In the step 2 describing processors, the 4th code snippet is displaying the same snippet than the 3rd one, while it should show the definition of the `avatar()` function according to the text around it

**Comment by stof** [comment]
Btw, how do these code references are working ? Are they random identifier referencing something stored externally from the git repo, or are the referencing something in the git repo ?

**Comment by stof** [comment]
Reading it again, the issue might actually be in the 3rd snippet showing the usage of the `<avatar()>` formatter too early

**Comment by weaverryan** [comment]
You're the first to notice that the code-blocks currently work in a mysterious way - I'm not surprised. I've just fixed the issue - you're right - I was being lazy, the 3rd snippet had the `<avatar()>` too early.

The code-blocks are a WIP experiment. There's a few pieces:
1) The tutorials are built in "steps". Each step is stored in a .diff file. An internal tool let's me walk through the steps, and edit earlier steps and have those changes merged to later steps. Ultimately, the .diff files are updated. Here is the "fix" that split one step into 2 pieces (for the 2 code blocks): sha: 12fee10f682392c37288ad374da14646a3a884ff

2) With the "steps", creating a code-block can be done by saying "which file", "which step" and "which lines" should be shown. I'd like to commit that metadata inline in the script, but for now, I just commit an "id" (sha: d171e5e1e7245fa810c6a3c11dfbf81fe41e7246). There is an internal service that associates that id with the file,step-key, lines, etc. Screenshot below for the curious

![screen shot 2015-01-16 at 10 13 12 am](https://cloud.githubusercontent.com/assets/121003/5778386/f3283d1a-9d68-11e4-8f03-6a619b687190.png)

It's still too cumbersome to create tutorials with this (and collaboration would really not yet be possible), but I hope to make writing tutorials a practice of writing code, then writing and selecting from that code. If the code changes later, the code-blocks would update. And there can be nice things like allowing users to see a diff between steps, download the code at a step, and do the code-block expanding. And I'd like to open this up... when the whole process doesn't suck :).

Anyways - thanks for the issue and the question!

**Comment by stof** [comment]
I see that some chapters are written in rST and others in Markdown in the repo (why mixing formats, btw ?). Seeing rST here gave me an idea.

In rST, Sphinx has a syntax to include an external file, highlighting some lines. You can have a look at https://raw.githubusercontent.com/FriendsOfSymfony/FOSHttpCache/master/doc/varnish-configuration.rst for an example (search for the `.. literalinclude` directive). AFAICT, the only missing info in this case compared to your service is the reference to the step, to get the right version.
This could serve as an inspiration to keep the whole code snippet information in the source directly rather than storing it in an external system (which means the git repo is not enough to contribute to the content).
This could even make the source a valid rST file, as rST is an extensible format (your md file is technically valid if you consider that `[[[ code('807df17ca4') ]]]` is part of the output, but it is not really the case)

but this discussion should probably live in a different place as it is about the KnpUniversity platform itself.

**Comment by weaverryan** [comment]
Interesting - I did not know about the literalinclude, but it's very identical (other than the step) to what I'm doing. In fact, I stopped using RST because, for practical reasons, it is less extensible (because I'm much less dangerous in Python, whereas I can extend an MD parser in PHP). But anyways, long-term, I could figure that out, I hear your point about the valid rST versus invented MD format.

If I _did_ create external files for the source, then included them like this, then those external files would still need to be generated by the command-line tool that helps walk through the steps. For example, if we wanted foo.php from step5, that doesn't _actually_ exist in the repo - it's only accessible if you "build up" to that step (using the tool), which applies diff's from steps 1-4 to get there. My point is that even though the physical file with the code-block would exist, it would need to be read-only. To truly update a code-block, you should edit the code of the project itself (e.g. move up to step5, make a change to the code, see that it's working, then use the tool to "compile" the new diff file). The whole idea is to put the code first, but it makes this part tricky.

And yes, this conversation should be elsewhere, but as everything is still private, there's nowhere else :). I will see if I can push the command-line builder behind all of this today.

**Comment by stof** [comment]
There is at least 2 PHP parsers for RST if you need to have it in PHP rather than Python (I don't know whether they are actually extendable as I haven't reviewed them yet): https://packagist.org/packages/gregwar/rst and https://packagist.org/packages/zetacomponents/document
